# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('name', models.CharField(max_length=128)),
                ('id', models.CharField(max_length=7, primary_key=True, serialize=False, unique=True)),
                ('credits', models.IntegerField(default=0)),
                ('rating', models.IntegerField(default=0)),
                ('grades', models.CharField(max_length=100)),
                ('prereq', models.CharField(max_length=100)),
                ('syllabus', models.TextField()),
            ],
        ),
    ]
