# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fruit',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
